project:
  type: website
  output-dir: docs

website:
  title: ""
  search: false
  back-to-top-navigation: true
  navbar: false
  page-navigation: true

  sidebar:
    style: docked
    collapse-level: 3
    contents:
      - text: 

      - text: Home
        href: qmd_dir/home.qmd

      - text: Need for MLOps
        href: qmd_dir/MLOps.qmd

      - text: Python resources
        href: qmd_dir/Python.qmd

      - section: ML Foundations
        contents:
          - text: Understanding dataset
            href: qmd_dir/dataset.qmd

          - text: Data Processing
            href: qmd_dir/data_processing.qmd
          - section: Algorithms
            contents:
              - text: Supervised Learning
                href: qmd_dir/supervised.qmd

              - text: Unsupervised Learning
                href: qmd_dir/unsupervised.qmd
    
      - text: Version Control
        href: qmd_dir/vc.qmd

      - text: Azure Cloud
        href: qmd_dir/azure.qmd

      - text: Containerization
        href: qmd_dir/containers.qmd

      - text: Data Engineering
        href: qmd_dir/DE.qmd

      - text: Model Registry
        href: qmd_dir/Registry.qmd

      - text: Testing & Deployment
        href: qmd_dir/Testing_deploying.qmd

      - text: Monitoring & Maintainance
        href: qmd_dir/monitoring_maintainance.qmd

      - text: Security & Best Practices
        href: qmd_dir/security_best_practices.qmd



format:
  html:
    theme: zephyr
    css: styles.css
    font:
      text: "Roboto"
      heading: "Roboto"
    toc: false
    include-before-body: _includes/navbar.html
    include-after-body: scripts/theme-toggle.js