project:
  type: website
  output-dir: _site

website:
  title: "MLSecOps Lab: Boeing x WIC x UW"
  favicon: favicon.svg
  search: false
  back-to-top-navigation: true
  navbar: false
  page-navigation: false

  sidebar:
    style: docked
    collapse-level: 3
    contents:
      - text: "{{< fa house >}} Home"
        href: index.qmd

      - text: "{{< fa rocket >}} Need for MLOps"
        href: MLOps.qmd

      - section: "{{< fa toolbox >}} Resources"
        contents:
          - text: "{{< fa python >}} Python Resources"
            href: Python.qmd
          - text: "{{< fa code-branch >}} Git Resources"
            href: git_resources.qmd

      - section: "{{< fa server >}} Infra Setup"
        contents:
          - text: "{{< fa cloud-arrow-up >}} Git to Azure"
            href: vc.qmd
          - text: "{{< fa cube >}} Terraform"
            href: terraform.qmd
          - text: "{{< fa diagram-project >}} ML Pipeline"
            href: ml_pipeline.qmd
          - text: "{{< fa download >}} Data Ingestion"
            href: data_ingestion.qmd

      - section: "{{< fa brain >}} ML Foundations"
        contents:
          - text: "{{< fa database >}} Understanding Dataset"
            href: dataset.qmd
          - text: "{{< fa gears >}} Data Processing"
            href: data_processing.qmd
          - section: "{{< fa chart-line >}} Algorithms"
            contents:
              - text: "{{< fa graduation-cap >}} Supervised Learning"
                href: supervised.qmd
              - text: "{{< fa magnifying-glass-chart >}} Unsupervised Learning"
                href: unsupervised.qmd
          - text: "{{< fa folder-open >}} Model Registry"
            href: Registry.qmd
          - text: "{{< fa flask >}} Endpoint Creation (Testing & Deployment)"
            href: Testing_deploying.qmd

      - text: "{{< fa chart-simple >}} Monitoring"
        href: monitoring_maintainance.qmd

      - text: "{{< fa shield-halved >}} Security & Best Practices"
        href: security_best_practices.qmd

      - text: "{{< fa flag-checkered >}} Going Forward & Endnotes"
        href: going_forward.qmd

format:
  html:
    theme: 
      light: [flatly, custom.scss]
      dark: [darkly, custom.scss]
    css: styles.css
    toc: false
    code-copy: true
    code-overflow: scroll
    highlight-style: 
      light: github
      dark: github-dark
    include-before-body: _includes/navbar.html
    include-after-body: 
      - _includes/footer.html
      - _includes/theme-toggle.js
    link-external-newwindow: true
    link-external-icon: true
