name: deploy-model-training-pipeline

on:
  workflow_dispatch:

jobs:
  get-config:
    uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: config-infra-prod.yml

  register-environment:
    needs: get-config
    uses: Azure/mlops-templates/.github/workflows/register-environment.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      environment_file: ML/environment.yaml
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}

  register-dataset:
    needs: get-config
    uses: Azure/mlops-templates/.github/workflows/register-dataset.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      name: taxi-data
      data_file: ML/data.yml
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}

  create-compute:
    needs: [get-config, register-environment, register-dataset]
    uses: Azure/mlops-templates/.github/workflows/create-compute.yml@main
    with:
      cluster_name: cpu-cluster
      size: Standard_DS3_v2
      min_instances: 0
      max_instances: 4
      cluster_tier: low_priority
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}

  run-pipeline:
    needs: [get-config, register-environment, create-compute, register-dataset]
    uses: Azure/mlops-templates/.github/workflows/run-pipeline.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      parameters-file: ML/pipeline.yml
      job-name: test
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
